### ISSUE TITLE
Tracking Scripting

### ISSUE THREAD

**Issue by Amouri21** [slackers123/Tarator#9]
- [x] compiling scripts
- [x] scripts macro
- [x] running scripts
- [x] running scripts natively (also recompile ecs)
- [x] propper scripting integration in ui etc..

**Comment by Amouri21** [comment]
- [ ] Compiling a rust script
- [ ] API: compileScripts(path) -> Set of Functions, JitEngine: interne Liste
- [ ] multithreading of scripts
- [ ] unit tests
